framework/yii/gii/controllers/DefaultController.php
<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

namespace yii\gii\controllers;

use Yii;
use yii\web\Controller;
use yii\web\HttpException;

/**
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @since 2.0
 */
class DefaultController extends Controller
{
	public $layout = 'generator';
	/**
	 * @var \yii\gii\Module
	 */
	public $module;
	/**
	 * @var \yii\gii\Generator
	 */
	public $generator;

	public function actionIndex()
	{
		$this->layout = 'main';
		return $this->render('index');
	}

	public function actionView($id)
	{
		$generator = $this->loadGenerator($id);
		$params = array('generator' => $generator, 'id' => $id);
		if (isset($_POST['preview']) || isset($_POST['generate'])) {
			if ($generator->validate()) {
				$generator->saveStickyAttributes();
				$files = $generator->generate();
				if (isset($_POST['generate']) && !empty($_POST['answers'])) {
					$params['hasError'] = $generator->save($files, (array)$_POST['answers'], $results);
					$params['results'] = $results;
				} else {
					$params['files'] = $files;
					$params['answers'] = isset($_POST['answers']) ? $_POST['answers'] : null;
				}
			}
		}

		return $this->render('view', $params);
	}

	public function actionPreview($id, $file)
	{
		$generator = $this->loadGenerator($id);
		if ($generator->validate()) {
			foreach ($generator->generate() as $f) {
				if ($f->id === $file) {
					$content = $f->preview();
					if ($content !== false) {
						return  '<div class="content">' . $content . '</content>';
					} else {
						return '<div class="error">Preview is not available for this file type.</div>';
					}
				}
			}
		}
		throw new HttpException(404, "Code file not found: $file");
	}

	public function actionDiff($id, $file)
	{
		$generator = $this->loadGenerator($id);
		if ($generator->validate()) {
			foreach ($generator->generate() as $f) {
				if ($f->id === $file) {
					return $this->renderPartial('diff', array(
						'diff' => $f->diff(),
					));
				}
			}
		}
		throw new HttpException(404, "Code file not found: $file");
	}

	/**
	 * Runs an action defined in the generator.
	 * Given an action named "xyz", the method "actionXyz()" in the generator will be called.
	 * If the method does not exist, a 400 HTTP exception will be thrown.
	 * @param string $id the ID of the generator
	 * @param string $name the action name
	 * @return mixed the result of the action.
	 * @throws HttpException if the action method does not exist.
	 */
	public function actionAction($id, $name)
	{
		$generator = $this->loadGenerator($id);
		$method = 'action' . $name;
		if (method_exists($generator, $method)) {
			return $generator->$method();
		} else {
			throw new HttpException(400, "Unknown generator action: $name");
		}
	}

	public function createUrl($route, $params = array())
	{
		if (!isset($params['id']) && $this->generator !== null) {
			foreach ($this->module->generators as $id => $generator) {
				if ($generator === $this->generator) {
					$params['id'] = $id;
					break;
				}
			}
		}
		return parent::createUrl($route, $params);
	}

	public function createActionUrl($name, $params = array())
	{
		foreach ($this->module->generators as $id => $generator) {
			if ($generator === $this->generator) {
				$params['id'] = $id;
				break;
			}
		}
		$params['name'] = $name;
		return parent::createUrl('action', $params);
	}

	/**
	 * Loads the generator with the specified ID.
	 * @param string $id the ID of the generator to be loaded.
	 * @return \yii\gii\Generator the loaded generator
	 * @throws \yii\web\HttpException
	 */
	protected function loadGenerator($id)
	{
		if (isset($this->module->generators[$id])) {
			$this->generator = $this->module->generators[$id];
			$this->generator->loadStickyAttributes();
			$this->generator->load($_POST);
			return $this->generator;
		} else {
			throw new HttpException(404, "Code generator not found: $id");
		}
	}
}

framework/yii/gii/views/default/diff.php
<?php
/**
 * @var yii\base\View $this
 * @var mixed $diff
 */
?>
<div class="default-diff">
	<?php if ($diff === false): ?>
		<div class="alert alert-danger">Diff is not supported for this file type.</div>
	<?php elseif (empty($diff)): ?>
		<div class="alert alert-success">Identical.</div>
	<?php else: ?>
		<div class="content"><?php echo $diff; ?></div>
	<?php endif; ?>
</div>

framework/yii/gii/views/default/index.php
<?php
use yii\helpers\Html;

/**
 * @var $this \yii\base\View
 * @var $content string
 * @var yii\gii\Generator[] $generators
 * @var yii\gii\Generator $activeGenerator
 */
$generators = Yii::$app->controller->module->generators;
$activeGenerator = Yii::$app->controller->generator;
$this->title = 'Welcome to Gii';
?>
<div class="default-index">
	<div class="page-header">
		<h1>Welcome to Gii <small>a magic tool that can write code for you</small></h1>
	</div>

	<p class="lead">Start the fun with the following code generators:</p>

	<div class="row">
		<?php foreach ($generators as $id => $generator): ?>
		<div class="generator col-lg-4">
			<h3><?php echo Html::encode($generator->getName()); ?></h3>
			<p><?php echo $generator->getDescription(); ?></p>
			<p><?php echo Html::a('Start »', array('default/view', 'id' => $id), array('class' => 'btn btn-default')); ?></p>
		</div>
		<?php endforeach; ?>
	</div>

	<p><a class="btn btn-success" href="http://www.yiiframework.com/extensions/?tag=gii">Get More Generators</a></p>

</div>

framework/yii/gii/views/default/view.php
<?php

use yii\gii\Generator;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\gii\components\ActiveField;
use yii\gii\CodeFile;

/**
 * @var yii\base\View $this
 * @var yii\gii\Generator $generator
 * @var string $id
 * @var yii\widgets\ActiveForm $form
 * @var string $results
 * @var boolean $hasError
 * @var CodeFile[] $files
 * @var array $answers
 */

$this->title = $generator->getName();
$templates = array();
foreach ($generator->templates as $name => $path) {
	$templates[$name] = "$name ($path)";
}
?>
<div class="default-view">
	<h1><?php echo Html::encode($this->title); ?></h1>

	<p><?php echo $generator->getDescription(); ?></p>

	<?php $form = ActiveForm::begin(array(
		'id' => "$id-generator",
		'successCssClass' => '',
		'fieldConfig' => array('class' => ActiveField::className()),
	)); ?>
		<div class="row">
			<div class="col-lg-8">
				<?php echo $this->renderFile($generator->formView(), array(
					'generator' => $generator,
					'form' => $form,
				)); ?>
				<?php echo $form->field($generator, 'template')->sticky()
					->label('Code Template')
					->dropDownList($templates)->hint('
						Please select which set of the templates should be used to generated the code.
				'); ?>
				<div class="form-group">
					<?php echo Html::submitButton('Preview', array('name' => 'preview', 'class' => 'btn btn-success')); ?>

					<?php if(isset($files)): ?>
						<?php echo Html::submitButton('Generate', array('name' => 'generate', 'class' => 'btn btn-danger')); ?>
					<?php endif; ?>
				</div>
			</div>
		</div>

		<?php
		if (isset($results)) {
			echo $this->render('view/results', array(
				'generator' => $generator,
				'results' => $results,
				'hasError' => $hasError,
			));
		} elseif (isset($files)) {
			echo $this->render('view/files', array(
				'generator' => $generator,
				'files' => $files,
				'answers' => $answers,
			));
		}
		?>
	<?php ActiveForm::end(); ?>
</div>

framework/yii/gii/views/default/view/files.php
<?php

use yii\gii\Generator;
use yii\helpers\Html;
use yii\gii\CodeFile;

/**
 * @var $this \yii\base\View
 * @var $generator \yii\gii\Generator
 * @var CodeFile[] $files
 * @var array $answers
 */
?>
<div class="default-view-files">
	<p>Click on the above <code>Generate</code> button to generate the files selected below:</p>

	<table class="table table-bordered table-striped table-condensed">
		<thead>
			<tr>
				<th class="file">Code File</th>
				<th class="action">Action</th>
				<th>
					<?php
					foreach ($files as $file) {
						if ($file->operation !== CodeFile::OP_SKIP) {
							echo '<input type="checkbox" id="check-all">';
							break;
						}
					}
					?>
				</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($files as $file): ?>
			<tr class="<?php echo $file->operation; ?>">
				<td class="file">
					<?php echo Html::a(Html::encode($file->getRelativePath()), array('preview', 'file' => $file->id), array('class' => 'preview-code', 'data-title' => $file->getRelativePath())); ?>
					<?php if ($file->operation === CodeFile::OP_OVERWRITE): ?>
						<?php echo Html::a('diff', array('diff', 'file' => $file->id), array('class' => 'diff-code label label-warning', 'data-title' => $file->getRelativePath())); ?>
					<?php endif; ?>
				</td>
				<td class="action">
					<?php
					if ($file->operation === CodeFile::OP_SKIP) {
						echo 'unchanged';
					} else {
						echo $file->operation;
					}
					?>
				</td>
				<td class="check">
					<?php
					if ($file->operation === CodeFile::OP_SKIP) {
						echo '&nbsp;';
					} else {
						echo Html::checkBox("answers[{$file->id}]", isset($answers) ? isset($answers[$file->id]) : ($file->operation === CodeFile::OP_NEW));
					}
					?>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>

	<div class="modal fade" id="preview-modal" tabindex="-1" role="dialog">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title">Modal title</h4>
				</div>
				<div class="modal-body">
					<p>Please wait ...</p>
				</div>
			</div>
		</div>
	</div>
</div>

framework/yii/gii/views/default/view/results.php
<?php

use yii\gii\Generator;
use yii\gii\CodeFile;

/**
 * @var yii\base\View $this
 * @var yii\gii\Generator $generator
 * @var string $results
 * @var boolean $hasError
 */
?>
<div class="default-view-results">
	<?php
	if ($hasError) {
		echo '<div class="alert alert-danger">There was something wrong when generating the code. Please check the following messages.</div>';
	} else {
		echo '<div class="alert alert-success">' . $generator->successMessage() . '</div>';
	}
	?>
	<pre><?php echo nl2br($results); ?></pre>
</div>

framework/yii/gii/views/layouts/generator.php
<?php
use yii\helpers\Html;

/**
 * @var $this \yii\base\View
 * @var $content string
 * @var yii\gii\Generator[] $generators
 * @var yii\gii\Generator $activeGenerator
 */
$generators = Yii::$app->controller->module->generators;
$activeGenerator = Yii::$app->controller->generator;
?>
<?php $this->beginContent('@yii/gii/views/layouts/main.php'); ?>
<div class="row">
	<div class="col-lg-3">
		<div class="list-group">
			<?php
			foreach ($generators as $id => $generator) {
				$label = '<i class="glyphicon glyphicon-chevron-right"></i>' . Html::encode($generator->getName());
				echo Html::a($label, array('default/view', 'id' => $id), array(
					'class' => $generator === $activeGenerator ? 'list-group-item active' : 'list-group-item',
				));
			}
			?>
		</div>
	</div>
	<div class="col-lg-9">
		<?php echo $content; ?>
	</div>
</div>
<?php $this->endContent(); ?>

framework/yii/gii/views/layouts/main.php
<?php
use yii\bootstrap\NavBar;
use yii\bootstrap\Nav;
use yii\helpers\Html;

/**
 * @var $this \yii\base\View
 * @var $content string
 */
$asset = yii\gii\GiiAsset::register($this);
?>
<?php $this->beginPage(); ?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8"/>
	<title><?php echo Html::encode($this->title); ?></title>
	<?php $this->head(); ?>
</head>
<body>
<?php $this->beginBody(); ?>
<?php
NavBar::begin(array(
	'brandLabel' => Html::img($asset->baseUrl . '/logo.png'),
	'brandUrl' => array('default/index'),
	'options' => array(
		'class' => 'navbar-inverse navbar-fixed-top',
	),
));
echo Nav::widget(array(
	'options' => array('class' => 'nav navbar-nav pull-right'),
	'items' => array(
		array('label' => 'Home', 'url' => array('default/index')),
		array('label' => 'Help', 'url' => 'http://www.yiiframework.com/doc/guide/topics.gii'),
		array('label' => 'Application', 'url' => Yii::$app->homeUrl),
	),
));
NavBar::end();
?>

<div class="container">
	<?php echo $content; ?>
</div>

<footer class="footer">
	<div class="container">
		<p class="pull-left">A Product of <a href="http://www.yiisoft.com/">Yii Software LLC</a></p>
		<p class="pull-right"><?php echo Yii::powered(); ?></p>
	</div>
</footer>

<?php $this->endBody(); ?>
</body>
</html>
<?php $this->endPage(); ?>